# Repo: MySpace/TemplateRepo
# File: azure-pipeline.yml

name: cicd_ci

pool:
  vmImage: 'ubuntu-20.04'

trigger:
  branches:
    include:
      - main

stages:
- stage: CI_Checks
  jobs:
  - job:
    displayName: yamllint_checks
    pool:
      vmImage: 'ubuntu-20.04	'
    steps:
    - script: |
        npm install 
      displayName: 'YAML Lint Checks'

